import type { Character } from '@/shared/types';

export const seedCharacters: Character[] = [
  {
    id: 'char-001', entityType: 'character',
    name: 'Thorvald Grimstone', typ: 'pc', rolle: 'Krieger',
    volk_spezies: 'Zwerg', beruf_klasse: 'Veteran / Söldner',
    alter: '187', geschlecht: 'Männlich', herkunft: 'Eisenberge des Nordens',
    fraktion_id: 'world-003', ort_id: 'world-001',
    status: 'active', sichtbarkeit: 'public',
    kurzbeschreibung: 'Ein grantiger Zwergenveteran mit einer dunklen Vergangenheit als Söldner. Sein grauer Bart und seine verwitterte Rüstung erzählen Geschichten von hundert Schlachten.',
    persoenlichkeit: 'Stoisch, direkt, widerwillig loyal. Misstraut Magiern und Adeligen instinktiv.',
    ziele: 'Den Tod seines alten Söldnertrupps rächen. Einen ehrenhaften Tod auf dem Schlachtfeld finden.',
    aengste: 'Im Schlaf sterben. Seinen Companions zur Last fallen.',
    schwaechen: 'Jähzorn. Kann eine Beleidigung seiner Ehre nicht ignorieren.',
    ideale: 'Treu deinen Waffenbrüdern bis zum Ende.',
    geheimnisse: 'Hat seinen früheren Befehlshaber verraten und ist dafür mitverantwortlich für den Tod seines alten Trupps.',
    hintergrund: 'Diente 50 Jahre lang in der Eisernen Gilde, einer legendären Söldnerkompanie. Nach ihrem Verrat und ihrer Vernichtung wanderte er jahrelang als Einzelkämpfer.',
    wichtige_ereignisse: 'Die Nacht von Ashenvale – Vernichtung der Eisernen Gilde. Begegnung mit Serafina in Kerlothaven.',
    ausruestung: 'Eiserne Kriegsaxt (+1), Kettenpanzer, Schildamulett der Gilde',
    faehigkeiten_werte_notizen: 'STR 18, CON 16, WIS 12. Spezialisierung: Zweihändige Waffen, Kampftaktik',
    tags: ['spielercharakter', 'veteran', 'zwerg', 'schwer-bewaffnet'],
    notes: 'Thorvald kennt den Standort eines alten Gildenverstecks.',
    metadata: {}, createdAt: '2024-01-15T10:00:00Z', updatedAt: '2024-03-20T08:30:00Z',
  },
  {
    id: 'char-002', entityType: 'character',
    name: 'Serafina Lacroix', typ: 'pc', rolle: 'Informationshändlerin',
    volk_spezies: 'Mensch', beruf_klasse: 'Schurkin / Schattenhändlerin',
    alter: '29', geschlecht: 'Weiblich', herkunft: 'Kerlothaven (Hafenstadt)',
    fraktion_id: '', ort_id: 'world-001',
    status: 'active', sichtbarkeit: 'public',
    kurzbeschreibung: 'Gewandtes Stadtmädchen, das sich durch Charme und Täuschung behauptet. Unter dem Lächeln verbirgt sich ein scharfes Kalkül.',
    persoenlichkeit: 'Charmant, berechnend, anpassungsfähig. Zeigt selten wahre Gefühle.',
    ziele: 'Die Eiserne Krone von innen zersetzen. Ihre verschollene Schwester finden.',
    aengste: 'In einer Falle sitzen, aus der kein Ausweg führt. Menschen zu verlieren, denen sie vertraut.',
    schwaechen: 'Rachegelüste überwältigen manchmal das rationale Denken.',
    ideale: 'Freiheit über alles – keine Kette, keine Schuld.',
    geheimnisse: 'Ist die uneheliche Tochter eines Ratsmitglieds der Eisernen Krone.',
    hintergrund: 'Wuchs in den Slums von Kerlothaven auf. Wurde von einer Diebesgilde aufgenommen und zur Meisterspionin ausgebildet.',
    wichtige_ereignisse: 'Erster Auftrag: Infiltration des Silbermond-Palastes. Begegnung mit Lady Vane.',
    ausruestung: 'Zwei Rapiere, Wurfmesser (x6), Shadowcloak, Dietrichset',
    faehigkeiten_werte_notizen: 'DEX 19, CHA 17, INT 15. Meisterin der Verkleidung und sozialen Manipulation.',
    tags: ['spielercharakter', 'mensch', 'schurkin', 'geheimagentin'],
    notes: '', metadata: {}, createdAt: '2024-01-15T10:05:00Z', updatedAt: '2024-03-18T14:20:00Z',
  },
  {
    id: 'char-003', entityType: 'character',
    name: 'Magistra Ysolde', typ: 'nsc', rolle: 'Mentorin',
    volk_spezies: 'Halbelfe', beruf_klasse: 'Hochmagierin / Archivarin',
    alter: '312', geschlecht: 'Weiblich', herkunft: 'Akademie der Fünf Türme',
    fraktion_id: 'world-004', ort_id: 'world-002',
    status: 'active', sichtbarkeit: 'gm_only',
    kurzbeschreibung: 'Eine würdevolle Hochmagierin mit silbernem Haar und dem Gewicht von Jahrhunderten hinter den Augen. Sie kennt mehr Geheimnisse als die meisten Bibliotheken.',
    persoenlichkeit: 'Bedächtig, verschlossen, aber warmherzig zu denen, die ihr Vertrauen verdienen.',
    ziele: 'Das Wissen der alten Welt vor der Eisernen Krone bewahren.',
    aengste: 'Die Bücher verbrennen zu sehen. Ihre Schüler sterben zu sehen.',
    schwaechen: 'Zögert zu lange, wenn Handeln nötig wäre.',
    ideale: 'Wissen ist Macht – und Verantwortung.',
    geheimnisse: 'Hat Kontakt zu einem verbotenen Orden, dem Ewigen Kreis, der die Eiserne Krone heimlich destabilisiert.',
    hintergrund: 'War einst am Hof der Eisernen Krone. Floh nach einem Streit mit dem Ersten Ratgeber.',
    wichtige_ereignisse: 'Übergabe des Schlüssels zum Geheimarchiv an die Gruppe.',
    ausruestung: 'Magischer Stab der Erkenntnis, Kodierbuch des Ewigen Kreises',
    faehigkeiten_werte_notizen: 'INT 21, WIS 19. Zugang zu 8th-Level-Zaubern.',
    tags: ['nsc', 'halbelfe', 'magierin', 'mentorin', 'geheimdienst'],
    notes: 'Ysolde kann bei magischen Rätseln helfen, erwartet aber Gegengaben.', metadata: {},
    createdAt: '2024-01-16T09:00:00Z', updatedAt: '2024-02-10T11:00:00Z',
  },
  {
    id: 'char-004', entityType: 'character',
    name: 'Korgan Blutfaust', typ: 'enemy', rolle: 'Antagonist',
    volk_spezies: 'Orc-Halbblut', beruf_klasse: 'Gildenchef / Kriegsherr',
    alter: '54', geschlecht: 'Männlich', herkunft: 'Torusk (Grenzfestung)',
    fraktion_id: 'world-003', ort_id: 'world-001',
    status: 'active', sichtbarkeit: 'gm_only',
    kurzbeschreibung: 'Brutaler Anführer der Eisenhauer-Gilde. Hat sich durch Einschüchterung und brutale Effizienz an die Spitze gearbeitet.',
    persoenlichkeit: 'Kalt, pragmatisch, einschüchternd. Respektiert nur Stärke.',
    ziele: 'Das Handelsmonopol in der Region vollständig kontrollieren. Die Eiserne Krone als stille Macht hinter dem Thron.',
    aengste: 'Schwäche zeigen. Von einem Stärkeren abgelöst zu werden.',
    schwaechen: 'Arroganz. Unterschätzt Gegner, die er für unter sich hält.',
    ideale: 'Macht ist das einzige Gesetz.',
    geheimnisse: 'Arbeitet heimlich für einen unbekannten Auftraggeber – Das Phantom.',
    hintergrund: 'Begann als Hehlerin in Kerlothaven. Übernahm die Eisenhauer-Gilde nach einem blutigen internen Putsch.',
    wichtige_ereignisse: 'Angriff auf Thorvalds alten Stützpunkt. Münzexplosion in Kerlothaven.',
    ausruestung: 'Runenschwert (gestohlenes Artefakt), Verstärkte Platte, Gildesiegel',
    faehigkeiten_werte_notizen: 'STR 20, CON 18. Veteran-Krieger, kennt keine Gnade.',
    tags: ['feind', 'antagonist', 'gildenchef', 'hauptantagonist'],
    notes: 'Korgan hat einen Informanten in der Gruppe – noch unbekannt wer.', metadata: {},
    createdAt: '2024-01-16T10:00:00Z', updatedAt: '2024-03-22T15:45:00Z',
  },
  {
    id: 'char-005', entityType: 'character',
    name: 'Lila „die Nadel"', typ: 'contact', rolle: 'Informantin',
    volk_spezies: 'Mensch', beruf_klasse: 'Straßenspionin',
    alter: '22', geschlecht: 'Weiblich', herkunft: 'Kerlothaven',
    fraktion_id: '', ort_id: 'world-001',
    status: 'active', sichtbarkeit: 'public',
    kurzbeschreibung: 'Winzige, unscheinbare Frau mit Augen, die nichts vergessen. Überlebt durch Informationen kaufen und verkaufen.',
    persoenlichkeit: 'Nervös, übervorsichtig, aber absolut zuverlässig wenn bezahlt.',
    ziele: 'Genug Geld verdienen um die Stadt zu verlassen.',
    aengste: 'Korgan Blutfaust. Die Nacht.',
    schwaechen: 'Verkauft Infos an den Meistbietenden.',
    ideale: 'Niemand verdient blindes Vertrauen.',
    geheimnisse: 'Weiß wo Korgan sein Schwarzbuch versteckt hält.',
    hintergrund: 'Wuchs als Waise auf, lernte das Überleben durch Beobachten.',
    wichtige_ereignisse: 'Hat der Gruppe den Hinweis auf das Geheimtreffen gegeben.',
    ausruestung: 'Nichts außer Wissen und schnellen Beinen.',
    faehigkeiten_werte_notizen: 'DEX 17, INT 14. Stadtkenntnis, Stealth.',
    tags: ['kontakt', 'informantin', 'mensch', 'nützlich'],
    notes: '', metadata: {}, createdAt: '2024-01-20T12:00:00Z', updatedAt: '2024-02-28T09:15:00Z',
  },
  {
    id: 'char-006', entityType: 'character',
    name: 'Bruder Aldric', typ: 'nsc', rolle: 'Priester / Ambivalenter Verbündeter',
    volk_spezies: 'Mensch', beruf_klasse: 'Priester des Lichtbringers',
    alter: '48', geschlecht: 'Männlich', herkunft: 'Silbermond-Kloster',
    fraktion_id: 'world-004', ort_id: 'world-002',
    status: 'active', sichtbarkeit: 'public',
    kurzbeschreibung: 'Ein Priester mit zu vielen Zweifeln für seinen Glauben und zu viel Glauben für seine Zweifel.',
    persoenlichkeit: 'Warmherzig, aber von inneren Konflikten zerrissen.',
    ziele: 'Das Richtige tun – wenn er nur wüsste was das ist.',
    aengste: 'Sein Gott hat ihn längst aufgegeben.',
    schwaechen: 'Entscheidungsschwäche in Krisensituationen.',
    ideale: 'Barmherzigkeit kennt keine Grenzen.',
    geheimnisse: 'Gewährt Korgan geheimen Zugang zum Kloster gegen Schutz seiner Gemeinde.',
    hintergrund: 'Diente 20 Jahre als Militärpfarrer. Kehrte gebrochen vom letzten Krieg zurück.',
    wichtige_ereignisse: 'Heilte Thorvald nach der Taverne-Schlägerei ohne Gegenforderung.',
    ausruestung: 'Heiliges Symbol, Kräuterbeutel, Kriegstagebuch', faehigkeiten_werte_notizen: 'WIS 16, CHA 14. Heilzauber (Level 5).',
    tags: ['nsc', 'priester', 'ambivalent', 'mensch'],
    notes: 'Aldric könnte ein wichtiger Verbündeter werden – oder ein Verräter.', metadata: {},
    createdAt: '2024-01-18T14:00:00Z', updatedAt: '2024-03-10T10:30:00Z',
  },
  {
    id: 'char-007', entityType: 'character',
    name: 'Lady Vane', typ: 'faction_rep', rolle: 'Adelshausvertreterin',
    volk_spezies: 'Mensch', beruf_klasse: 'Diplomatin / Politikerin',
    alter: '41', geschlecht: 'Weiblich', herkunft: 'Adelhaus Silbermond',
    fraktion_id: 'world-004', ort_id: 'world-002',
    status: 'active', sichtbarkeit: 'gm_only',
    kurzbeschreibung: 'Eiskalte Diplomatin mit einem Lächeln wie Seidenpapier – schön und gefährlich dünn.',
    persoenlichkeit: 'Geschliffene Manieren, brutales Kalkül dahinter.',
    ziele: 'Das Adelhaus Silbermond an die Macht bringen und die Eisenhauer-Gilde zerschlagen.',
    aengste: 'Politischen Einfluss verlieren.',
    schwaechen: 'Vertraut zu sehr der Macht der Worte.',
    ideale: 'Adel verpflichtet – zur Macht.',
    geheimnisse: 'Hat einen alten Pakt mit Magistra Ysolde. Sucht das Phantom.',
    hintergrund: 'Tochter des verstorbenen Ersten Ministers. Hat das Haus nach seinem Tod übergenommen.',
    wichtige_ereignisse: 'Angebot an die Gruppe: Information gegen Loyalität.',
    ausruestung: 'Vergifteter Ring, kodierter Briefstapel', faehigkeiten_werte_notizen: 'CHA 20, INT 18. Meisterin der politischen Intrige.',
    tags: ['fraktionsvertreterin', 'adel', 'mensch', 'antagonistin'],
    notes: 'Vane spielt ihr eigenes Spiel. Niemals völlig vertrauen.', metadata: {},
    createdAt: '2024-01-19T08:00:00Z', updatedAt: '2024-03-15T16:00:00Z',
  },
  {
    id: 'char-008', entityType: 'character',
    name: 'Das Phantom', typ: 'other', rolle: 'Unbekannte Bedrohung',
    volk_spezies: 'Unbekannt', beruf_klasse: 'Unbekannt',
    alter: 'Unbekannt', geschlecht: 'Unbekannt', herkunft: 'Unbekannt',
    fraktion_id: '', ort_id: '',
    status: 'unknown', sichtbarkeit: 'gm_only',
    kurzbeschreibung: 'Jemand – oder etwas – zieht im Hintergrund die Fäden. Korgan berichtet von einem Auftraggeber, den niemand je gesehen hat.',
    persoenlichkeit: 'Unbekannt. Handlungen deuten auf Geduld und Weitblick hin.',
    ziele: 'Unbekannt. Scheint an der Destabilisierung der Region interessiert.',
    aengste: 'Unbekannt.',
    schwaechen: 'Unbekannt.',
    ideale: 'Unbekannt.',
    geheimnisse: 'Ist möglicherweise jemand aus dem engsten Umfeld der Gruppe.',
    hintergrund: 'Existiert seit mindestens 10 Jahren als Geheimfigur in der Unterwelt.',
    wichtige_ereignisse: 'Erste Erwähnung in Korgans gestohlenen Notizen.',
    ausruestung: 'Unbekannt', faehigkeiten_werte_notizen: 'Alle Stats unbekannt.',
    tags: ['mysterium', 'phantom', 'hauptbedrohung', 'geheimnis'],
    notes: 'Der GM weiß: Das Phantom ist [SPOILER REDACTED]. Nicht enthüllen vor Session 8.', metadata: {},
    createdAt: '2024-01-20T20:00:00Z', updatedAt: '2024-03-22T20:00:00Z',
  },
];
