import type { CalendarEvent } from '@/shared/types';
import { generateId, now } from '@/shared/utils/helpers';

export const seedEvents: CalendarEvent[] = [
  {
    id: generateId(),
    entityType: 'calendar_event',
    campaignId: 'default',
    title: 'Geburt von Thorvald Grimstone',
    description: 'Thorvald wurde in den tiefen Minen der Eisenberge geboren.',
    day: 12,
    month: 5,
    year: 793,
    status: 'active',
    linkedEntityId: 'char-001',
    linkedEntityType: 'character',
    tags: ['geburtstag', 'zwerg'],
    notes: '',
    metadata: {},
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: generateId(),
    entityType: 'calendar_event',
    campaignId: 'default',
    title: 'Die Nacht von Ashenvale',
    description: 'Die Eiserne Gilde wurde durch Verrat beinahe vollständig vernichtet. Thorvald verlor alle seine Waffenbrüder.',
    day: 18,
    month: 10,
    year: 975,
    status: 'active',
    linkedEntityId: 'char-001',
    linkedEntityType: 'character',
    tags: ['schlacht', 'verlust'],
    notes: '',
    metadata: {},
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: generateId(),
    entityType: 'calendar_event',
    campaignId: 'default',
    title: 'Gründung von Kerlothaven',
    description: 'Der erste Stein für den Hafen von Kerlothaven wurde gelegt. Ein historischer Tag für den Handel.',
    day: 1,
    month: 3,
    year: 500,
    status: 'active',
    linkedEntityId: 'world-001',
    linkedEntityType: 'place',
    tags: ['gründung', 'stadt'],
    notes: '',
    metadata: {},
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: generateId(),
    entityType: 'calendar_event',
    campaignId: 'default',
    title: 'Erster Auftrag: Infiltration Silbermond',
    description: 'Serafina Lacroix schlich sich zum ersten Mal erfolgreich in den Silbermond-Palast ein.',
    day: 14,
    month: 8,
    year: 978,
    status: 'active',
    linkedEntityId: 'char-002',
    linkedEntityType: 'character',
    tags: ['mission', 'erfolg'],
    notes: '',
    metadata: {},
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: generateId(),
    entityType: 'calendar_event',
    campaignId: 'default',
    title: 'Münzexplosion',
    description: 'Ein Anschlag in Kerlothaven, inszeniert von Korgan Blutfaust, der die Stadt erschütterte.',
    day: 5,
    month: 11,
    year: 979,
    status: 'active',
    linkedEntityId: 'char-004',
    linkedEntityType: 'character',
    tags: ['anschlag', 'verbrechen'],
    notes: '',
    metadata: {},
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: generateId(),
    entityType: 'calendar_event',
    campaignId: 'default',
    title: 'Übergabe des Schlüssels',
    description: 'Magistra Ysolde überreichte in tiefster Nacht den Schlüssel zum Geheimarchiv an die Gruppe.',
    day: 28,
    month: 1,
    year: 980,
    status: 'active',
    linkedEntityId: 'char-003',
    linkedEntityType: 'character',
    tags: ['geheimnis', 'artefakt'],
    notes: '',
    metadata: {},
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: generateId(),
    entityType: 'calendar_event',
    campaignId: 'default',
    title: 'Aufstieg der Eisernen Krone',
    description: 'Die Fraktion der Eisernen Krone übernimmt offiziell die politische Macht über die Region.',
    day: 10,
    month: 0,
    year: 960,
    status: 'active',
    linkedEntityId: 'world-003',
    linkedEntityType: 'faction',
    tags: ['politik', 'machtwechsel'],
    notes: '',
    metadata: {},
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: generateId(),
    entityType: 'calendar_event',
    campaignId: 'default',
    title: 'Heilung im Silbermond-Kloster',
    description: 'Bruder Aldric rettet Thorvald nach der berüchtigten Tavernen-Schlägerei das Leben.',
    day: 22,
    month: 4,
    year: 980,
    status: 'active',
    linkedEntityId: 'char-006',
    linkedEntityType: 'character',
    tags: ['heilung', 'begegnung'],
    notes: '',
    metadata: {},
    createdAt: now(),
    updatedAt: now(),
  },
];
