import type { Character } from '@/shared/types';

export const seedCharacters: Character[] = [
  {
    id: 'char-001', entityType: 'character',
    name: 'Thorvald Grimstone', type: 'pc', role: 'Krieger',
    species: 'Zwerg', profession_class: 'Veteran / Söldner',
    age: '187', gender: 'Männlich', origin: 'Eisenberge des Nordens',
    faction_id: 'world-003', location_id: 'world-001',
    status: 'active', visibility: 'public',
    short_description: 'Ein grantiger Zwergenveteran mit einer dunklen Vergangenheit als Söldner. Sein grauer Bart und seine verwitterte Rüstung erzählen Geschichten von hundert Schlachten.',
    personality: 'Stoisch, direkt, widerwillig loyal. Misstraut Magiern und Adeligen instinktiv.',
    goals: 'Den Tod seines alten Söldnertrupps rächen. Einen ehrenhaften Tod auf dem Schlachtfeld finden.',
    fears: 'Im Schlaf sterben. Seinen Companions zur Last fallen.',
    weaknesses: 'Jähzorn. Kann eine Beleidigung seiner Ehre nicht ignorieren.',
    ideals: 'Treu deinen Waffenbrüdern bis zum Ende.',
    secrets: 'Hat seinen früheren Befehlshaber verraten und ist dafür mitverantwortlich für den Tod seines alten Trupps.',
    background: 'Diente 50 Jahre lang in der Eisernen Gilde, einer legendären Söldnerkompanie. Nach ihrem Verrat und ihrer Vernichtung wanderte er jahrelang als Einzelkämpfer.',
    important_events: 'Die Nacht von Ashenvale – Vernichtung der Eisernen Gilde. Begegnung mit Serafina in Kerlothaven.',
    equipment: 'Eiserne Kriegsaxt (+1), Kettenpanzer, Schildamulett der Gilde',
    skills_stats_notes: 'STR 18, CON 16, WIS 12. Spezialisierung: Zweihändige Waffen, Kampftaktik',
    tags: ['spielercharakter', 'veteran', 'zwerg', 'schwer-bewaffnet'],
    portraitUrl: '/images/thorvald.png',
    notes: 'Thorvald kennt den Standort eines alten Gildenverstecks.',
    metadata: {}, createdAt: '2024-01-15T10:00:00Z', updatedAt: '2024-03-20T08:30:00Z', campaignId: 'default',
  },
  {
    id: 'char-002', entityType: 'character',
    name: 'Serafina Lacroix', type: 'pc', role: 'Informationshändlerin',
    species: 'Mensch', profession_class: 'Schurkin / Schattenhändlerin',
    age: '29', gender: 'Weiblich', origin: 'Kerlothaven (Hafenstadt)',
    faction_id: '', location_id: 'world-001',
    status: 'active', visibility: 'public',
    short_description: 'Gewandtes Stadtmädchen, das sich durch Charme und Täuschung behauptet. Unter dem Lächeln verbirgt sich ein scharfes Kalkül.',
    personality: 'Charmant, berechnend, anpassungsfähig. Zeigt selten wahre Gefühle.',
    goals: 'Die Eiserne Krone von innen zersetzen. Ihre verschollene Schwester finden.',
    fears: 'In einer Falle sitzen, aus der kein Ausweg führt. Menschen zu verlieren, denen sie vertraut.',
    weaknesses: 'Rachegelüste überwältigen manchmal das rationale Denken.',
    ideals: 'Freiheit über alles – keine Kette, keine Schuld.',
    secrets: 'Ist die uneheliche Tochter eines Ratsmitglieds der Eisernen Krone.',
    background: 'Wuchs in den Slums von Kerlothaven auf. Wurde von einer Diebesgilde aufgenommen und zur Meisterspionin ausgebildet.',
    important_events: 'Erster Auftrag: Infiltration des Silbermond-Palastes. Begegnung mit Lady Vane.',
    equipment: 'Zwei Rapiere, Wurfmesser (x6), Shadowcloak, Dietrichset',
    skills_stats_notes: 'DEX 19, CHA 17, INT 15. Meisterin der Verkleidung und sozialen Manipulation.',
    tags: ['spielercharakter', 'mensch', 'schurkin', 'geheimagentin'],
    notes: '', metadata: {}, createdAt: '2024-01-15T10:05:00Z', updatedAt: '2024-03-18T14:20:00Z', campaignId: 'default',
  },
  {
    id: 'char-003', entityType: 'character',
    name: 'Magistra Ysolde', type: 'nsc', role: 'Mentorin',
    species: 'Halbelfe', profession_class: 'Hochmagierin / Archivarin',
    age: '312', gender: 'Weiblich', origin: 'Akademie der Fünf Türme',
    faction_id: 'world-004', location_id: 'world-002',
    status: 'active', visibility: 'gm_only',
    short_description: 'Eine würdevolle Hochmagierin mit silbernem Haar und dem Gewicht von Jahrhunderten hinter den Augen. Sie kennt mehr Geheimnisse als die meisten Bibliotheken.',
    personality: 'Bedächtig, verschlossen, aber warmherzig zu denen, die ihr Vertrauen verdienen.',
    goals: 'Das Wissen der alten Welt vor der Eisernen Krone bewahren.',
    fears: 'Die Bücher verbrennen zu sehen. Ihre Schüler sterben zu sehen.',
    weaknesses: 'Zögert zu lange, wenn Handeln nötig wäre.',
    ideals: 'Wissen ist Macht – und Verantwortung.',
    secrets: 'Hat Kontakt zu einem verbotenen Orden, dem Ewigen Kreis, der die Eiserne Krone heimlich destabilisiert.',
    background: 'War einst am Hof der Eisernen Krone. Floh nach einem Streit mit dem Ersten Ratgeber.',
    important_events: 'Übergabe des Schlüssels zum Geheimarchiv an die Gruppe.',
    equipment: 'Magischer Stab der Erkenntnis, Kodierbuch des Ewigen Kreises',
    skills_stats_notes: 'INT 21, WIS 19. Zugang zu 8th-Level-Zaubern.',
    tags: ['nsc', 'halbelfe', 'magierin', 'mentorin', 'geheimdienst'],
    portraitUrl: '/images/elara.png',
    notes: 'Ysolde kann bei magischen Rätseln helfen, erwartet aber Gegengaben.', metadata: {},
    createdAt: '2024-01-16T09:00:00Z', updatedAt: '2024-02-10T11:00:00Z', campaignId: 'default',
  },
  {
    id: 'char-004', entityType: 'character',
    name: 'Korgan Blutfaust', type: 'enemy', role: 'Antagonist',
    species: 'Orc-Halbblut', profession_class: 'Gildenchef / Kriegsherr',
    age: '54', gender: 'Männlich', origin: 'Torusk (Grenzfestung)',
    faction_id: 'world-003', location_id: 'world-001',
    status: 'active', visibility: 'gm_only',
    short_description: 'Brutaler Anführer der Eisenhauer-Gilde. Hat sich durch Einschüchterung und brutale Effizienz an die Spitze gearbeitet.',
    personality: 'Kalt, pragmatisch, einschüchternd. Respektiert nur Stärke.',
    goals: 'Das Handelsmonopol in der Region vollständig kontrollieren. Die Eiserne Krone als stille Macht hinter dem Thron.',
    fears: 'Schwäche zeigen. Von einem Stärkeren abgelöst zu werden.',
    weaknesses: 'Arroganz. Unterschätzt Gegner, die er für unter sich hält.',
    ideals: 'Macht ist das einzige Gesetz.',
    secrets: 'Arbeitet heimlich für einen unbekannten Auftraggeber – Das Phantom.',
    background: 'Begann als Hehlerin in Kerlothaven. Übernahm die Eisenhauer-Gilde nach einem blutigen internen Putsch.',
    important_events: 'Angriff auf Thorvalds alten Stützpunkt. Münzexplosion in Kerlothaven.',
    equipment: 'Runenschwert (gestohlenes Artefakt), Verstärkte Platte, Gildesiegel',
    skills_stats_notes: 'STR 20, CON 18. Veteran-Krieger, kennt keine Gnade.',
    tags: ['feind', 'antagonist', 'gildenchef', 'hauptantagonist'],
    notes: 'Korgan hat einen Informanten in der Gruppe – noch unbekannt wer.', metadata: {},
    createdAt: '2024-01-16T10:00:00Z', updatedAt: '2024-03-22T15:45:00Z', campaignId: 'default',
  },
  {
    id: 'char-005', entityType: 'character',
    name: 'Lila „die Nadel"', type: 'contact', role: 'Informantin',
    species: 'Mensch', profession_class: 'Straßenspionin',
    age: '22', gender: 'Weiblich', origin: 'Kerlothaven',
    faction_id: '', location_id: 'world-001',
    status: 'active', visibility: 'public',
    short_description: 'Winzige, unscheinbare Frau mit Augen, die nichts vergessen. Überlebt durch Informationen kaufen und verkaufen.',
    personality: 'Nervös, übervorsichtig, aber absolut zuverlässig wenn bezahlt.',
    goals: 'Genug Geld verdienen um die Stadt zu verlassen.',
    fears: 'Korgan Blutfaust. Die Nacht.',
    weaknesses: 'Verkauft Infos an den Meistbietenden.',
    ideals: 'Niemand verdient blindes Vertrauen.',
    secrets: 'Weiß wo Korgan sein Schwarzbuch versteckt hält.',
    background: 'Wuchs als Waise auf, lernte das Überleben durch Beobachten.',
    important_events: 'Hat der Gruppe den Hinweis auf das Geheimtreffen gegeben.',
    equipment: 'Nichts außer Wissen und schnellen Beinen.',
    skills_stats_notes: 'DEX 17, INT 14. Stadtkenntnis, Stealth.',
    tags: ['kontakt', 'informantin', 'mensch', 'nützlich'],
    notes: '', metadata: {}, createdAt: '2024-01-20T12:00:00Z', updatedAt: '2024-02-28T09:15:00Z', campaignId: 'default',
  },
  {
    id: 'char-006', entityType: 'character',
    name: 'Bruder Aldric', type: 'nsc', role: 'Priester / Ambivalenter Verbündeter',
    species: 'Mensch', profession_class: 'Priester des Lichtbringers',
    age: '48', gender: 'Männlich', origin: 'Silbermond-Kloster',
    faction_id: 'world-004', location_id: 'world-002',
    status: 'active', visibility: 'public',
    short_description: 'Ein Priester mit zu vielen Zweifeln für seinen Glauben und zu viel Glauben für seine Zweifel.',
    personality: 'Warmherzig, aber von inneren Konflikten zerrissen.',
    goals: 'Das Richtige tun – wenn er nur wüsste was das ist.',
    fears: 'Sein Gott hat ihn längst aufgegeben.',
    weaknesses: 'Entscheidungsschwäche in Krisensituationen.',
    ideals: 'Barmherzigkeit kennt keine Grenzen.',
    secrets: 'Gewährt Korgan geheimen Zugang zum Kloster gegen Schutz seiner Gemeinde.',
    background: 'Diente 20 Jahre als Militärpfarrer. Kehrte gebrochen vom letzten Krieg zurück.',
    important_events: 'Heilte Thorvald nach der Taverne-Schlägerei ohne Gegenforderung.',
    equipment: 'Heiliges Symbol, Kräuterbeutel, Kriegstagebuch', skills_stats_notes: 'WIS 16, CHA 14. Heilzauber (Level 5).',
    tags: ['nsc', 'priester', 'ambivalent', 'mensch'],
    notes: 'Aldric könnte ein wichtiger Verbündeter werden – oder ein Verräter.', metadata: {},
    createdAt: '2024-01-18T14:00:00Z', updatedAt: '2024-03-10T10:30:00Z', campaignId: 'default',
  },
  {
    id: 'char-007', entityType: 'character',
    name: 'Lady Vane', type: 'faction_rep', role: 'Adelshausvertreterin',
    species: 'Mensch', profession_class: 'Diplomatin / Politikerin',
    age: '41', gender: 'Weiblich', origin: 'Adelhaus Silbermond',
    faction_id: 'world-004', location_id: 'world-002',
    status: 'active', visibility: 'gm_only',
    short_description: 'Eiskalte Diplomatin mit einem Lächeln wie Seidenpapier – schön und gefährlich dünn.',
    personality: 'Geschliffene Manieren, brutales Kalkül dahinter.',
    goals: 'Das Adelhaus Silbermond an die Macht bringen und die Eisenhauer-Gilde zerschlagen.',
    fears: 'Politischen Einfluss verlieren.',
    weaknesses: 'Vertraut zu sehr der Macht der Worte.',
    ideals: 'Adel verpflichtet – zur Macht.',
    secrets: 'Hat einen alten Pakt mit Magistra Ysolde. Sucht das Phantom.',
    background: 'Tochter des verstorbenen Ersten Ministers. Hat das Haus nach seinem Tod übergenommen.',
    important_events: 'Angebot an die Gruppe: Information gegen Loyalität.',
    equipment: 'Vergifteter Ring, kodierter Briefstapel', skills_stats_notes: 'CHA 20, INT 18. Meisterin der politischen Intrige.',
    tags: ['fraktionsvertreterin', 'adel', 'mensch', 'antagonistin'],
    notes: 'Vane spielt ihr eigenes Spiel. Niemals völlig vertrauen.', metadata: {},
    createdAt: '2024-01-19T08:00:00Z', updatedAt: '2024-03-15T16:00:00Z', campaignId: 'default',
  },
  {
    id: 'char-008', entityType: 'character',
    name: 'Das Phantom', type: 'other', role: 'Unbekannte Bedrohung',
    species: 'Unbekannt', profession_class: 'Unbekannt',
    age: 'Unbekannt', gender: 'Unbekannt', origin: 'Unbekannt',
    faction_id: '', location_id: '',
    status: 'unknown', visibility: 'gm_only',
    short_description: 'Jemand – oder etwas – zieht im Background die Fäden. Korgan berichtet von einem Auftraggeber, den niemand je gesehen hat.',
    personality: 'Unbekannt. Handlungen deuten auf Geduld und Weitblick hin.',
    goals: 'Unbekannt. Scheint an der Destabilisierung der Region interessiert.',
    fears: 'Unbekannt.',
    weaknesses: 'Unbekannt.',
    ideals: 'Unbekannt.',
    secrets: 'Ist möglicherweise jemand aus dem engsten Umfeld der Gruppe.',
    background: 'Existiert seit mindestens 10 Jahren als Geheimfigur in der Unterwelt.',
    important_events: 'Erste Erwähnung in Korgans gestohlenen Notizen.',
    equipment: 'Unbekannt', skills_stats_notes: 'Alle Stats unbekannt.',
    tags: ['mysterium', 'phantom', 'hauptbedrohung', 'geheimnis'],
    notes: 'Der GM weiß: Das Phantom ist [SPOILER REDACTED]. Nicht enthüllen vor Session 8.', metadata: {},
    createdAt: '2024-01-20T20:00:00Z', updatedAt: '2024-03-22T20:00:00Z', campaignId: 'default',
  },
];
