import type { Character } from '@/shared/types';

export const cthulhuCharacters: Character[] = [
  {
    id: 'cth-char-001', entityType: 'character',
    name: 'Arthur Vance', type: 'pc', role: 'Privatdetektiv',
    species: 'Mensch', profession_class: 'Ermittler / Veteran',
    age: '34', gender: 'Männlich', origin: 'Boston, Massachusetts',
    faction_id: '', location_id: 'cth-world-001',
    status: 'active', visibility: 'public',
    short_description: 'Ein zynischer Privatdetektiv im Trenchcoat. Seine Erlebnisse im Großen Krieg haben Spuren hinterlassen, die er im Alkohol zu ertränken sucht.',
    personality: 'Hartgesotten, pragmatisch, misstrauisch gegenüber Autoritäten. Versteckt ein weiches Herz unter rauer Schale.',
    goals: 'Herausfinden, was wirklich mit seinem alten Kameraden Thomas passiert ist.',
    fears: 'Enge, dunkle Gräben. Das unaufhörliche Kratzen hinter den Wänden.',
    weaknesses: 'Alkoholismus (Trinkt, um die Albträume zu vergessen).',
    ideals: 'Jemand muss für die kleinen Leute einstehen.',
    secrets: 'Hat im Krieg einen Vorgesetzten erschossen, um seine Einheit zu retten.',
    background: 'Ehemaliger Soldat (AEF), jetzt Privatdetektiv in Boston mit einem Büro, das seine besten Tage hinter sich hat.',
    important_events: 'Die Schützengraben von Argonne (1918).',
    equipment: '.38 Special Revolver, Flachmann, Taschenlampe, Dietriche',
    skills_stats_notes: 'STR 60, CON 50, SIZ 65, DEX 70, APP 40, EDU 60, INT 75, POW 50. Schusswaffen (Kurzwaffen) 60%, Verborgenes Erkennen 70%',
    tags: ['spielercharakter', 'detektiv', 'veteran'],
    portraitUrl: '/images/vance_portrait.png',
    notes: 'Vance hat neuerdings Halluzinationen von schwarzen Tentakeln.',
    metadata: {}, createdAt: '1925-09-01T08:00:00Z', updatedAt: '1925-09-05T10:00:00Z', campaignId: 'cthulhu',
  },
  {
    id: 'cth-char-002', entityType: 'character',
    name: 'Margaret Finch', type: 'pc', role: 'Archivarin',
    species: 'Mensch', profession_class: 'Bibliothekarin / Okkultistin',
    age: '28', gender: 'Weiblich', origin: 'Arkham, Massachusetts',
    faction_id: '', location_id: 'cth-world-002',
    status: 'active', visibility: 'public',
    short_description: 'Brillante junge Archivarin an der Miskatonic University. Fühlt sich zwischen staubigen Büchern wohler als unter Menschen.',
    personality: 'Neugierig, pedantisch, schüchtern aber äußerst furchtlos, wenn es um Wissen geht.',
    goals: 'Die verschollene lateinische Übersetzung des Necronomicons finden.',
    fears: 'Dass das Wissen der Menschheit nicht ausreicht, um die nahende Dunkelheit aufzuhalten.',
    weaknesses: 'Kann einem Geheimnis nicht widerstehen, selbst wenn es tödlich ist.',
    ideals: 'Wissen ist Licht.',
    secrets: 'Hat illegal Zugangsberechtigungen zum Orne-Archiv gefälscht.',
    background: 'In Arkham aufgewachsen. War immer fasziniert von den alten Büchern und Sprachen. Sie hat heimlich Zugang zum Restricted Section der Bibliothek erlangt.',
    important_events: 'Entdeckung der geheimen Notizen von Prof. Armitage kurz vor seinem Verschwinden.',
    equipment: 'Starke Taschenlampe, Lateinwörterbuch, Tränengas-Sprüher.',
    skills_stats_notes: 'Bibliotheksnutzung 80%, Latein 50%, Okkultismus 30%. Stabilität: 60.',
    tags: ['spielercharakter', 'gelehrte', 'miskatonic'],
    portraitUrl: '/images/finch_portrait.png',
    notes: '', metadata: {}, createdAt: '1925-09-01T11:00:00Z', updatedAt: '1925-09-05T11:00:00Z', campaignId: 'cthulhu',
  },
  {
    id: 'cth-char-003', entityType: 'character',
    name: 'Silas Thorne', type: 'enemy', role: 'Kultanführer',
    species: 'Mensch(?)', profession_class: 'Industrieller / Hohepriester',
    age: '55', gender: 'Männlich', origin: 'Neuengland',
    faction_id: 'cth-world-004', location_id: 'cth-world-003',
    status: 'active', visibility: 'gm_only',
    short_description: 'Ein charismatischer und immens reicher Reeder, der Arkham mit eiserner Faust kontrolliert – und im Verborgenen blutige Rituale leitet.',
    personality: 'Arrogant, charmant, absolut skrupellos.',
    goals: 'Das Tor öffnen, um "Ihn, der in der Dunkelheit weilt" zu befreien.',
    fears: 'Zu sterben, bevor das Ritual vollendet ist.',
    weaknesses: 'Narzissmus. Glaubt, er könne Götter kontrollieren.',
    ideals: 'Macht ist das einzige universelle Recht.',
    secrets: 'Ist in Wahrheit viel älter, als er aussieht – er nutzt Rituale, um seinen Alterungsprozess aufzuhalten.',
    background: 'Erbe der Thorne Shipping Company. Hat seinen Reichtum durch den Handel mit seltsamen Artefakten aus Ägypten verzehnfacht.',
    important_events: 'Die Ermordung seines Rivalen (1919). Erwerb von Blackwood Manor (1922).',
    equipment: 'Gehstock mit Silberknauf, Zeremonieller Dolch, Schutzamulett',
    skills_stats_notes: 'STR 50, CON 80, SIZ 60, DEX 50, APP 70, EDU 75, INT 85, POW 90. Cthulhu-Mythos 45%, Überreden 80%',
    tags: ['antagonist', 'kultist', 'reich'],
    portraitUrl: '/images/thorne_portrait.png',
    notes: 'Thorne hat überall in der Polizei Informanten.', metadata: {},
    createdAt: '1925-09-01T10:00:00Z', updatedAt: '1925-09-05T12:00:00Z', campaignId: 'cthulhu',
  },
  {
    id: 'cth-char-004', entityType: 'character',
    name: 'Das Ding im Keller', type: 'creature', role: 'Monster',
    species: 'Dimensionaler Schlurfer', profession_class: '-',
    age: 'Zeitlos', gender: 'Unbekannt', origin: 'Zwischen den Dimensionen',
    faction_id: 'cth-world-004', location_id: 'cth-world-003',
    status: 'active', visibility: 'gm_only',
    short_description: 'Eine grauenhafte, insektenartige Monstrosität, die von Thorne beschworen wurde, um unliebsame Besucher im Blackwood Manor zu "entsorgen".',
    personality: 'Aggressiv, hungrig, gehorcht nur demjenigen, der das Amulett von Ptah trägt.',
    goals: 'Fressen. In seine eigene Dimension zurückkehren.',
    fears: 'Das Zeichen der Älteren.',
    weaknesses: 'Empfindlich gegen starkes Licht und Feuer.',
    ideals: '-',
    secrets: 'Versteckt sich in einer Taschendimension hinter dem Heizungskeller.',
    background: 'Wurde 1924 von Thorne gebunden.',
    important_events: 'Das Verschwinden von Detective Malone.',
    equipment: 'Klauen, Tentakel',
    skills_stats_notes: 'STR 120, CON 100, SIZ 140, DEX 40, INT 20, POW 50. Angriff (Klaue) 60% (1D8+DB)',
    tags: ['monster', 'mythos', 'boss'],
    notes: 'Angriff führt zu Stabilitätsverlust (1/1D10).', metadata: {},
    createdAt: '1925-09-01T11:00:00Z', updatedAt: '1925-09-05T13:00:00Z', campaignId: 'cthulhu',
  }
];
