import type { GameplayEntity } from '@/shared/types';

export const seedGameplayEntities: GameplayEntity[] = [
  {
    id: 'game-001', entityType: 'quest', title: 'Das Schwarzbuch',
    summary: 'Beschafft Korgans Schwarzbuch aus dem Eisenhauer-Hauptquartier.',
    description: 'Lila hat verraten, dass Korgan ein Schwarzbuch mit Beweisen für alle seine Verbrechen führt. Das Buch ist in seinem persönlichen Büro im Tiefen Lager eingeschlossen. Die Gruppe muss hinein – wie auch immer.',
    status: 'active', difficulty: 'hard',
    related_character_ids: ['char-004', 'char-005'],
    related_faction_ids: ['world-003'],
    related_place_ids: ['world-001'],
    consequences: 'Mit dem Buch können sie Korgan erpressen, ihn anklagen oder es für Lady Vane verwenden.',
    related_reward_ids: ['game-007'],
    related_scene_ids: ['game-003'],
    goal: 'Das Schwarzbuch aus Korgans Büro stehlen.',
    giver: 'Selbst initiiert / Lila als Tipp',
    progress: 'Gruppe hat Grundriss des Lagers beschafft.',
    outcome: '',
    tags: ['hauptquest', 'heist', 'korgan'],
    notes: 'Mehrere mögliche Wege: Stealth, Bestechung, Gewalt, Ablenkung.', metadata: {},
    createdAt: '2024-01-20T09:00:00Z', updatedAt: '2024-03-22T10:00:00Z', campaignId: 'default',
  },
  {
    id: 'game-002', entityType: 'quest', title: 'Die Lady und ihr Preis',
    summary: 'Lady Vane bietet Informationen gegen bedingungslose Loyalität.',
    description: 'Lady Vane hat die Gruppe einberufen. Sie weiß etwas über das Phantom – aber sie will dafür Garantien. Die Gruppe muss eine Aufgabe für das Adelhaus erledigen oder die Informationen woanders suchen.',
    status: 'open', difficulty: 'medium',
    related_character_ids: ['char-007', 'char-003'],
    related_faction_ids: ['world-004'],
    related_place_ids: ['world-002'],
    consequences: 'Abhängig von der Entscheidung: Verbündete oder Feindschaft des Adelshauses.',
    related_reward_ids: [],
    related_scene_ids: ['game-004'],
    goal: 'Herausfinden wer das Phantom ist – durch Vane oder auf eigene Faust.',
    giver: 'Lady Vane',
    progress: 'Noch nicht begonnen.',
    outcome: '',
    tags: ['hauptquest', 'politisch', 'information'],
    notes: 'Moral-Dilemma: Vane ist manipulativ aber informiert.', metadata: {},
    createdAt: '2024-01-21T10:00:00Z', updatedAt: '2024-03-15T11:00:00Z', campaignId: 'default',
  },
  {
    id: 'game-003', entityType: 'scene', title: 'Einbruch ins Tiefe Lager',
    summary: 'Die Gruppe infiltriert das Eisenhauer-Hauptquartier.',
    description: 'Das Tiefe Lager ist ein ehemaliger Hangar, umgebaut zu Lager, Büros und Verhörräumen. Korgans Büro liegt im zweiten Stock. Wächter patrouillieren im 4-Minuten-Takt. Im Keller: Gefangene, die von den Spielern gerettet oder ignoriert werden können.',
    status: 'open', difficulty: 'hard',
    related_character_ids: ['char-004'],
    related_faction_ids: ['world-003'],
    related_place_ids: ['world-001'],
    consequences: 'Erfolg = Schwarzbuch. Fehlschlag = Hinterhalt durch Korgan.',
    related_reward_ids: [],
    related_scene_ids: [],
    place_id: 'world-001',
    scene_goal: 'Schwarzbuch aus Korgans Büro entwenden, unentdeckt das Lager verlassen.',
    conflict_type: 'Stealth / Kampf hybrid',
    participants: 'Gruppe vs. Eisenhauer-Wächter (6), Korgan (evtl.)',
    possible_twist: 'Aldric ist im Keller gefangen. Retten sie ihn, machen sie Lärm.',
    tags: ['szene', 'heist', 'stealth', 'hauptszene'],
    notes: 'Wichtig: Wandkarte des Lagers vorbereiten.', metadata: {},
    createdAt: '2024-01-22T09:00:00Z', updatedAt: '2024-03-20T08:00:00Z', campaignId: 'default',
  },
  {
    id: 'game-004', entityType: 'scene', title: 'Empfang bei Lady Vane',
    summary: 'Formeller Empfang im Silbermond-Palast – Infos, Forderungen, Verhandlung.',
    description: 'Ein aufwendig inszenierter Abendempfang. Vane nutzt die gesellschaftliche Kulisse, um die Gruppe zu testen und zu verhandeln. Wie verhalten sich die Charaktere in höfischer Atmosphäre? Wer lässt sich von der Fassade täuschen?',
    status: 'open', difficulty: 'medium',
    related_character_ids: ['char-007', 'char-003'],
    related_faction_ids: ['world-004'],
    related_place_ids: ['world-002'],
    consequences: 'Soziales Verhandlungsergebnis bestimmt die Questrichtung.',
    related_reward_ids: [],
    related_scene_ids: [],
    place_id: 'world-002',
    scene_goal: 'Informationen über das Phantom extrahieren.',
    conflict_type: 'Sozial / Verhandlung',
    participants: 'Gruppe + Lady Vane + Magistra Ysolde (Überraschung)',
    possible_twist: 'Ysolde erscheint und widerspricht Vanes Version der Ereignisse.',
    tags: ['szene', 'sozial', 'palast', 'enthüllung'],
    notes: 'Soll die politische Komplexität der Welt zeigen.', metadata: {},
    createdAt: '2024-01-23T10:00:00Z', updatedAt: '2024-03-10T12:00:00Z', campaignId: 'default',
  },
  {
    id: 'game-005', entityType: 'encounter', title: 'Runenfalle im Archiv',
    summary: 'Das Geheimarchiv Ysoldes ist durch alte Zwergrunenfallen gesichert.',
    description: 'Als die Gruppe das Archiv betritt, aktivieren Runenfallen der alten Zwergenkultur. Magische Schutzwesen werden beschworen. Nur wer die Runenschrift entziffern kann (Thorvald, Ysolde), kann die Fallen entschärfen.',
    status: 'open', difficulty: 'medium',
    related_character_ids: ['char-001', 'char-003'],
    related_faction_ids: [],
    related_place_ids: ['world-002'],
    consequences: 'Entschärfung = Zugang zum Archiv. Fehlschlag = magischer Schaden + Alarm.',
    related_reward_ids: [],
    related_scene_ids: [],
    encounter_type: 'Magische Falle + Rätsel',
    enemies_or_participants: 'Runengeister (3, Level 4)',
    possible_outcomes: 'Entschärfen, Kämpfen, Umgehen durch Runenlesen.',
    tags: ['begegnung', 'runen', 'rätsel', 'archiv'],
    notes: 'Thorvald hat hier die Chance zu glänzen – Wissensüberprüfung.', metadata: {},
    createdAt: '2024-01-24T09:00:00Z', updatedAt: '2024-02-15T10:00:00Z', campaignId: 'default',
  },
  {
    id: 'game-006', entityType: 'session_log', title: 'Session 1 – Ankunft in Kerlothaven',
    summary: 'Erste Session: Ankunft, erste Begegnungen, Auftaktszene.',
    description: 'Die Gruppe kam auf unterschiedlichen Wegen nach Kerlothaven. Im Hafen-Gasthaus „Zwischen Zwei Welten" kam es zur ersten Begegnung mit Lila, die ihnen von Korgans Schwarzbuch erzählte. Thorvald erkannte einen alten Gildensöldner unter Korgans Männern.',
    status: 'completed',
    related_character_ids: ['char-001', 'char-002', 'char-005'],
    related_faction_ids: ['world-003'],
    related_place_ids: ['world-001'],
    consequences: 'Gruppe ist jetzt auf Korgans Radar. Lila als Kontakt etabliert.',
    related_reward_ids: [],
    related_scene_ids: [],
    session_number: 1,
    session_date: '2024-03-01',
    open_threads: 'Wer ist der Informant in Korgans Reihen? Was bedeutet das Phantom-Symbol auf dem Brief?',
    new_hooks: 'Lila erwähnte ein Treffen in drei Tagen. Thorvald sah jemanden den er tot glaubte.',
    affected_entity_ids: ['char-001', 'char-002', 'char-005', 'game-001'],
    tags: ['sessionlog', 'session-1', 'start'],
    notes: 'Atmosärisch gut. Gruppe gut eingespielt.', metadata: {},
    createdAt: '2024-03-01T22:00:00Z', updatedAt: '2024-03-02T10:00:00Z', campaignId: 'default',
  },
  {
    id: 'game-007', entityType: 'reward', title: 'Schwarzbuch-Informationen',
    summary: 'Zugang zu Korgans gesammelten Geheimnissen und Kontakten.',
    description: 'Das Schwarzbuch enthält Beweise gegen Stadtratsmitglieder, Erpressungsopfer und Korgans direkten Draht zum Phantom. Mit diesen Informationen können die Charaktere politische Schachzüge machen, Verbündete gewinnen oder Feinde neutralisieren.',
    status: 'open',
    related_character_ids: ['char-004'],
    related_faction_ids: ['world-003'],
    related_place_ids: [],
    consequences: 'Kann die politische Lage der Stadt grundlegend verändern.',
    related_reward_ids: [],
    related_scene_ids: ['game-003'],
    tags: ['belohnung', 'information', 'politisch'],
    notes: 'Inhalt des Buches je nach Spielerfortschritt enthüllen.', metadata: {},
    createdAt: '2024-01-25T10:00:00Z', updatedAt: '2024-03-22T11:00:00Z', campaignId: 'default',
  },
  {
    id: 'game-008', entityType: 'mechanic', title: 'Reputation & Fraktionsgunst',
    summary: 'Tracking der Fraktionsbeziehungen über einen Punkt-Score.',
    description: 'Jede Fraktion hat einen Score von -5 (Feind) bis +5 (Verbündeter). Handlungen verändern den Score. Bei +3 können Fraktionen aktiv helfen. Bei -3 schicken sie Auftragsmörder. Scoreänderungen werden im Session-Log festgehalten.',
    status: 'active',
    related_character_ids: [],
    related_faction_ids: ['world-003', 'world-004'],
    related_place_ids: [],
    consequences: 'Motiviert strategisches Denken beim Umgang mit Fraktionen.',
    related_reward_ids: [],
    related_scene_ids: [],
    tags: ['mechanik', 'system', 'fraktionen', 'meta'],
    notes: 'Aktuelle Scores: Eisenhauer -4, Silbermond +1, Klerus 0.', metadata: {},
    createdAt: '2024-01-26T11:00:00Z', updatedAt: '2024-03-22T10:00:00Z', campaignId: 'default',
  },
];
