import type { Relationship } from '@/shared/types';

export const seedRelationships: Relationship[] = [
  {
    id: 'rel-001', entityType: 'relationship',
    source_character_id: 'char-001', target_character_id: 'char-002',
    relationship_type: 'friendship', direction: 'symmetric',
    intensity: 4, attitude: 'positive', visibility: 'public', status: 'active',
    description: 'Thorvald und Serafina kennen sich seit dem Überfall auf das Lagerhaus. Er misstraut ihr ein wenig, aber ihr Mut hat ihn beeindruckt.',
    history: 'Trafen sich in Kerlothaven nach dem Überfall. Kämpften Seite an Seite gegen Korgans Männer.',
    tags: [], notes: '', metadata: {}, createdAt: '2024-01-20T10:00:00Z', updatedAt: '2024-02-15T14:00:00Z', campaignId: 'default',
  },
  {
    id: 'rel-002', entityType: 'relationship',
    source_character_id: 'char-003', target_character_id: 'char-001',
    relationship_type: 'mentor_student', direction: 'directed',
    intensity: 3, attitude: 'positive', visibility: 'public', status: 'active',
    description: 'Ysolde hat Thorvald in alten Runen unterrichtet und kennt seinen Ehrenkodex.',
    history: 'Ysolde begegnete Thorvald nach dessen Wanderjahren und erkannte sein Potenzial als Beschützer.',
    tags: [], notes: '', metadata: {}, createdAt: '2024-01-22T09:00:00Z', updatedAt: '2024-02-10T11:00:00Z', campaignId: 'default',
  },
  {
    id: 'rel-003', entityType: 'relationship',
    source_character_id: 'char-004', target_character_id: 'char-001',
    relationship_type: 'enmity', direction: 'directed',
    intensity: 5, attitude: 'negative', visibility: 'public', status: 'active',
    description: 'Korgan verantwortete den Untergang der Eisernen Gilde. Thorvald schwor Rache.',
    history: 'Vor 30 Jahren befahl Korgan den Verrat an der Eisernen Gilde. Thorvald überlebte als Einziger.',
    tags: [], notes: '', metadata: {}, createdAt: '2024-01-22T10:00:00Z', updatedAt: '2024-03-01T08:00:00Z', campaignId: 'default',
  },
  {
    id: 'rel-004', entityType: 'relationship',
    source_character_id: 'char-007', target_character_id: 'char-003',
    relationship_type: 'alliance', direction: 'symmetric',
    intensity: 3, attitude: 'neutral', visibility: 'gm_only', status: 'active',
    description: 'Lady Vane und Magistra Ysolde haben einen alten Geheimpakt gegen die Eiserne Krone.',
    history: 'Beide verloren Menschen durch die Eisenhauer-Gilde. Ein stilles Bündnis entstand.',
    tags: [], notes: 'Nur GM weiß davon.', metadata: {}, createdAt: '2024-01-23T11:00:00Z', updatedAt: '2024-02-20T15:30:00Z', campaignId: 'default',
  },
  {
    id: 'rel-005', entityType: 'relationship',
    source_character_id: 'char-005', target_character_id: 'char-002',
    relationship_type: 'acquaintance', direction: 'symmetric',
    intensity: 2, attitude: 'neutral', visibility: 'public', status: 'active',
    description: 'Lila und Serafina kennen sich aus der Unterwelt. Rein geschäftlich.',
    history: 'Serafina hat Lila bereits dreimal für Informationen bezahlt.',
    tags: [], notes: '', metadata: {}, createdAt: '2024-01-24T13:00:00Z', updatedAt: '2024-02-25T10:00:00Z', campaignId: 'default',
  },
  {
    id: 'rel-006', entityType: 'relationship',
    source_character_id: 'char-008', target_character_id: 'char-004',
    relationship_type: 'loyalty', direction: 'directed',
    intensity: 4, attitude: 'negative', visibility: 'gm_only', status: 'active',
    description: 'Korgan gehorcht dem Phantom, aus Angst oder Überzeugung – unklar.',
    history: 'Das Phantom hat Korgan vor 10 Jahren aus einer lebensbedrohlichen Situation gerettet.',
    tags: [], notes: 'Korgan kennt das Phantom nicht persönlich – nur durch Boten.', metadata: {},
    createdAt: '2024-01-25T14:00:00Z', updatedAt: '2024-03-10T09:00:00Z', campaignId: 'default',
  },
  {
    id: 'rel-007', entityType: 'relationship',
    source_character_id: 'char-006', target_character_id: 'char-004',
    relationship_type: 'debt_obligation', direction: 'directed',
    intensity: 3, attitude: 'negative', visibility: 'gm_only', status: 'active',
    description: 'Aldric gewährt Korgan Zugang zum Kloster gegen Schutz seiner Gemeinde.',
    history: 'Nach dem Brand des Armenviertels suchte Aldric Schutz bei Korgan – ein Pakt den er bereut.',
    tags: [], notes: 'Dies macht Aldric zu einem unfreiwilligen Verräter.', metadata: {},
    createdAt: '2024-01-26T15:00:00Z', updatedAt: '2024-03-05T12:00:00Z', campaignId: 'default',
  },
  {
    id: 'rel-008', entityType: 'relationship',
    source_character_id: 'char-002', target_character_id: 'char-007',
    relationship_type: 'rivalry', direction: 'symmetric',
    intensity: 3, attitude: 'mixed', visibility: 'public', status: 'active',
    description: 'Serafina misstraut Vanes politischen Spielchen. Vane sieht in Serafina ein nützlich-gefährliches Tier.',
    history: 'Erste Begegnung beim Infiltrationsauftrag im Silbermond-Palast.',
    tags: [], notes: '', metadata: {}, createdAt: '2024-01-27T16:00:00Z', updatedAt: '2024-02-28T11:00:00Z', campaignId: 'default',
  },
  {
    id: 'rel-009', entityType: 'relationship',
    source_character_id: 'char-001', target_character_id: 'char-006',
    relationship_type: 'acquaintance', direction: 'symmetric',
    intensity: 2, attitude: 'positive', visibility: 'public', status: 'active',
    description: 'Thorvald schätzt Aldrics Pragmatismus trotz seines Priestenmantels.',
    history: 'Aldric heilte Thorvald nach einem Kampf ohne Gegenleistung zu fordern.',
    tags: [], notes: '', metadata: {}, createdAt: '2024-01-28T09:00:00Z', updatedAt: '2024-02-20T08:00:00Z', campaignId: 'default',
  },
  {
    id: 'rel-010', entityType: 'relationship',
    source_character_id: 'char-003', target_character_id: 'char-007',
    relationship_type: 'secret_connection', direction: 'symmetric',
    intensity: 4, attitude: 'positive', visibility: 'secret', status: 'active',
    description: 'Ysolde und Vane teilen das Wissen um den Standort der alten Reichsinsignien.',
    history: 'Entdeckt, als Ysolde einen 200 Jahre alten Brief im Archiv fand, adressiert an Vanes Vorfahren.',
    tags: [], notes: 'Absolutes Geheimnis – nur GM.', metadata: {},
    createdAt: '2024-01-29T10:00:00Z', updatedAt: '2024-02-15T16:00:00Z', campaignId: 'default',
  },
  {
    id: 'rel-011', entityType: 'relationship',
    source_character_id: 'char-005', target_character_id: 'char-004',
    relationship_type: 'enmity', direction: 'directed',
    intensity: 5, attitude: 'negative', visibility: 'gm_only', status: 'active',
    description: 'Korgan ließ Lilas Bruder töten. Sie weiß es und wartet auf Gelegenheit zur Rache.',
    history: 'Vor zwei Jahren wurde ihr Bruder Marcus als Warnung für andere Informanten getötet.',
    tags: [], notes: 'Lila als potenzielle Verbündete – sie hat Informationen über Korgans Schwarzbuch.', metadata: {},
    createdAt: '2024-01-30T11:00:00Z', updatedAt: '2024-03-01T09:00:00Z', campaignId: 'default',
  },
  {
    id: 'rel-012', entityType: 'relationship',
    source_character_id: 'char-008', target_character_id: 'char-002',
    relationship_type: 'secret_connection', direction: 'directed',
    intensity: 2, attitude: 'mixed', visibility: 'secret', status: 'active',
    description: 'Das Phantom scheint Serafina zu beobachten – ihre Abstammung ist ihm bekannt.',
    history: 'Eine unbekannte Figur ließ ihr eine verschlüsselte Nachricht zukommen, die ihren wahren Vater erwähnte.',
    tags: [], notes: 'Kann in Session 8+ enthüllt werden.', metadata: {},
    createdAt: '2024-02-01T12:00:00Z', updatedAt: '2024-03-20T14:00:00Z', campaignId: 'default',
  },
];
