import type { WorldEntity } from '@/shared/types';

export const seedWorldEntities: WorldEntity[] = [
  {
    id: 'world-001', entityType: 'place', title: 'Kerlothaven',
    category: 'place', summary: 'Geschäftige Hafenstadt an der Kreuzung der alten Kaiserstraßen.',
    description: 'Eine Stadt, die aus drei Welten besteht: dem reichen Hochviertel der Kaufleute, dem Labyrinth der Slums und dem korrupten Hafen. Kerlothaven ist das wirtschaftliche Herz der Region – und ihr Krebsgeschwür.',
    tags: ['hafenstadt', 'hauptort', 'korrupt', 'urban'],
    status: 'active', region_id: 'world-001',
    faction_id: 'world-003',
    related_character_ids: ['char-001', 'char-002', 'char-004', 'char-005'],
    related_gameplay_ids: ['game-001', 'game-003'],
    historical_references: ['world-005'],
    imageUrl: '/images/kerlothaven.png',
    notes: 'Spieler können hier Verhöre, Hehlerei und politische Intrigen erleben.',
    metadata: {}, createdAt: '2024-01-10T09:00:00Z', updatedAt: '2024-03-20T10:00:00Z', campaignId: 'default',
  },
  {
    id: 'world-002', entityType: 'place', title: 'Silbermond-Palast',
    category: 'place', summary: 'Prunkvoll zerfallener Sitz des Adelshauses Silbermond.',
    description: 'Einst der prächtigste Bau der Region. Heute ein mehrdeutiges Symbol – glänzend außen, modrig innen. Lady Vane residiert hier und empfängt Besucher in Hallen, deren Grandeur die schwindende Macht des Adels überdecken soll.',
    tags: ['adel', 'palast', 'intrigenort', 'repräsentativ'],
    status: 'active', region_id: '',
    faction_id: 'world-004',
    related_character_ids: ['char-003', 'char-006', 'char-007'],
    related_gameplay_ids: ['game-002'],
    historical_references: [],
    imageUrl: '/images/silbermond.png',
    notes: 'Der Keller des Palastes führt zu einem alten Tunnelsystem.',
    metadata: {}, createdAt: '2024-01-10T09:30:00Z', updatedAt: '2024-03-10T12:00:00Z', campaignId: 'default',
  },
  {
    id: 'world-003', entityType: 'faction', title: 'Eisenhauer-Gilde',
    category: 'faction', summary: 'Brutalste Handelsgilde der Region. Kontrolliert Häfen und Schwarzmarkt.',
    description: 'Die Eisenhauer sind dem Namen nach eine Handelsvereinigung. In Wahrheit sind sie organisiertes Verbrechen in Frack und Siegel. Unter Korgan Blutfausts Führung haben sie Konkurrenten zerstört, Stadträte gekauft und die Stadtwache korrumpiert.',
    tags: ['gilde', 'kriminell', 'mächtig', 'antagonisten'],
    status: 'active', region_id: 'world-001',
    faction_id: '',
    related_character_ids: ['char-001', 'char-004'],
    related_gameplay_ids: ['game-001', 'game-004'],
    historical_references: [],
    notes: 'Spieler können von innen heraus infiltrieren oder extern angreifen.',
    metadata: {}, createdAt: '2024-01-11T10:00:00Z', updatedAt: '2024-03-22T09:00:00Z', campaignId: 'default',
  },
  {
    id: 'world-004', entityType: 'faction', title: 'Adelhaus Silbermond',
    category: 'faction', summary: 'Altes Adelshaus am Rand der Bedeutungslosigkeit. Kämpft um Relevanz.',
    description: 'Das Silbermond-Haus war einst die mächtigste Adelssippe der Region. Heute sind sie reich an Geschichte und arm an politischem Einfluss. Lady Vane versucht durch Bündnisse und Information diesen Verfall aufzuhalten.',
    tags: ['adel', 'politisch', 'verbündete', 'fragil'],
    status: 'active', region_id: '',
    faction_id: '',
    related_character_ids: ['char-003', 'char-006', 'char-007'],
    related_gameplay_ids: ['game-002'],
    historical_references: ['world-005'],
    notes: 'Kann zu Verbündeten werden, wenn die Gruppe ihren Interessen nützt.',
    metadata: {}, createdAt: '2024-01-11T11:00:00Z', updatedAt: '2024-02-20T14:00:00Z', campaignId: 'default',
  },
  {
    id: 'world-005', entityType: 'history', title: 'Der Große Brand von Kerlothaven',
    category: 'history', summary: 'Vor 15 Jahren brannte ein Drittel der Stadt. Offizielle Ursache: Unfall.',
    description: 'Der Brand vernichtete das Armenviertel und die Altstadt. Tausende starben oder wurden obdachlos. Die offizielle Version spricht von einem Lagerhausbrand. Tatsächlich war es ein gezielter Anschlag der damaligen Eisenhauer-Führung, um die Konkurrenz der freien Händler zu vernichten.',
    tags: ['historisch', 'katastrophe', 'verschwörung', 'kerlothaven'],
    status: 'active', region_id: 'world-001',
    faction_id: 'world-003',
    related_character_ids: ['char-004', 'char-006'],
    related_gameplay_ids: [],
    historical_references: [],
    notes: 'Beweis dafür ist in Korgans Schwarzbuch. Könnte politische Erschütterungen auslösen wenn enthüllt.',
    metadata: {}, createdAt: '2024-01-12T09:00:00Z', updatedAt: '2024-02-15T11:00:00Z', campaignId: 'default',
  },
  {
    id: 'world-006', entityType: 'artifact', title: 'Das Schwarzbuch Korgans',
    category: 'artifact', summary: 'Verschlüsseltes Lederbuch mit allen Korgans Verbrechen und Kontakten.',
    description: 'Ein abgegriffenes schwarzes Lederbuch, gesichert mit einem magischen Schloss. Enthält Namen, Daten und Beweise für 20 Jahre Korruption, Mord und Erpressung. Einige Einträge betreffen hochrangige Stadtratsmitglieder.',
    tags: ['artefakt', 'beweismittel', 'politisch', 'gefährlich'],
    status: 'active', region_id: '',
    faction_id: 'world-003',
    related_character_ids: ['char-004', 'char-005'],
    related_gameplay_ids: ['game-001'],
    historical_references: ['world-005'],
    notes: 'Aufenthaltsort: Geheimfach in Korgans Büro, Tiefes Lager, Eisenhauer-Hauptquartier.',
    metadata: {}, createdAt: '2024-01-13T10:00:00Z', updatedAt: '2024-03-22T15:00:00Z', campaignId: 'default',
  },
  {
    id: 'world-007', entityType: 'lore', title: 'Die Eiserne Krone (Legende)',
    category: 'lore', summary: 'Mythische Herrscherkrone, die dem rechtmäßigen Herrscher der Region wahre Macht verleihen soll.',
    description: 'Alte Legenden berichten von einer Krone, geschmiedet aus dem Eisen eines gefallenen Sterns und den Ringen sieben besiegter Könige. Wer sie trägt, dem gehorchen die alten Mächte. Historiker halten dies für Propaganda. Einige magische Quellen widersprechen dem.',
    tags: ['legende', 'artefakt', 'macht', 'politisch', 'mythisch'],
    status: 'mythical', region_id: '',
    faction_id: '',
    related_character_ids: ['char-003', 'char-007', 'char-008'],
    related_gameplay_ids: [],
    historical_references: ['world-005'],
    notes: 'Die Eiserne Krone ist der namensgebende MacGuffin der Kampagne. Standort: unbekannt.',
    metadata: {}, createdAt: '2024-01-14T08:00:00Z', updatedAt: '2024-02-10T12:00:00Z', campaignId: 'default',
  },
  {
    id: 'world-008', entityType: 'culture', title: 'Die Hafenkultur von Kerlothaven',
    category: 'culture', summary: 'Raue, pragmatische Kultur der Seeleute, Söldner und Händler.',
    description: 'In Kerlothaven zählt nicht Herkunft, sondern was du kannst und was du weißt. Duell-Tradition bei Ehrverletzungen. Starke Aberglauben rund um das Meer. Gastfreundschaft gegenüber ehrlichen Händlern, null Toleranz für Verräter.',
    tags: ['kultur', 'hafen', 'urban', 'gesellschaft'],
    status: 'active', region_id: 'world-001',
    faction_id: '',
    related_character_ids: ['char-001', 'char-002', 'char-005'],
    related_gameplay_ids: [],
    historical_references: [],
    notes: 'Wichtig für Rollenspielhintergründe und soziale Interaktionen.',
    metadata: {}, createdAt: '2024-01-15T09:00:00Z', updatedAt: '2024-02-01T10:00:00Z', campaignId: 'default',
  },
  {
    id: 'world-009', entityType: 'magic_tech', title: 'Alte Runenschrift des Nordens',
    category: 'magic_tech', summary: 'Uraltes Schriftsystem, das Magie in Stein binden kann.',
    description: 'Entwickelt von den Zwergen der Eisenberge in der Frühzeit. Runenschriften können Magie in physische Objekte binden – Türen versiegeln, Fallen aktivieren, Informationen verschlüsseln. Nur wenige Lebende können sie noch lesen.',
    tags: ['magie', 'runen', 'zwerg', 'altes-wissen'],
    status: 'active', region_id: '',
    faction_id: '',
    related_character_ids: ['char-001', 'char-003'],
    related_gameplay_ids: ['game-005'],
    historical_references: [],
    notes: 'Thorvald kann einfache Runen lesen. Ysolde beherrscht sie vollständig.',
    metadata: {}, createdAt: '2024-01-16T10:00:00Z', updatedAt: '2024-02-05T11:00:00Z', campaignId: 'default',
  },
  {
    id: 'world-010', entityType: 'religion', title: 'Der Lichtbringer-Kult',
    category: 'religion', summary: 'Verbreitete Staatsreligion. Ambivalente Haltung gegenüber der weltlichen Macht.',
    description: 'Der Lichtbringer ist ein Wohlstandsgott, der Ordnung, Handel und Gerechtigkeit verkörpert. Sein Klerus ist reich, verbreitet und tief in politische Strukturen eingewoben. Bruder Aldric ist ein untypischer Vertreter: Er glaubt an die Armen, nicht an die Macht.',
    tags: ['religion', 'kult', 'politik', 'klerus'],
    status: 'active', region_id: '',
    faction_id: '',
    related_character_ids: ['char-006'],
    related_gameplay_ids: [],
    historical_references: ['world-005'],
    notes: 'Der Obere Klerus ist korrumpiert und mit der Eisenhauer-Gilde verbündet.',
    metadata: {}, createdAt: '2024-01-17T09:00:00Z', updatedAt: '2024-02-10T13:00:00Z', campaignId: 'default',
  },
];
